modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
[[mods]]
modId="skinlayers3d"
version="1.1.0"
displayName="3dSkinLayers"
authors="tr7zw"
description='''
Renders the player skin layer in 3d
'''
[[dependencies.skinlayers3d]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.skinlayers3d]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="CLIENT"
